version: "3.8"
services:
  database:
    container_name: influxDB
    image: influx-image
    restart: always
    ports:
      - "8086:8086"
    build:
      context: .
      dockerfile: influx/Dockerfile
    networks:
      default:
        aliases:
          - influxDB
  broker:
    container_name: rabbit
    image: rabbit-image
    restart: always
    ports:
      - "1883:1883"
      - "15672:15672"
      - "5672:5672"
    build:
      context: .
      dockerfile: rabbit/Dockerfile
    networks:
      default:
        aliases:
          - rabbit
  gui:
    container_name: grafana
    image: grafana-image
    restart: always
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: grafana/Dockerfile
    depends_on:
      - database

  telegraf:
    container_name: telegraf
    image: telegraf-image
    restart: always
    build:
      context: .
      dockerfile: telegraf/Dockerfile
    environment:
      - INFLUX_TOKEN=BOTwqQSKrj8S9vuKB1VyzRv6yQJk5P8jdVl4HEYAS-a3X2g9XKCyTbuiRuY2EH4lg9hwQ19508PP1z_ylBoihg==
    command: --config http://influxDB:8086/api/v2/telegrafs/0aa9d76b14922000
    depends_on:
      - database

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24
